# -----------------------------------------------------------------------------
# Template Config
# -----------------------------------------------------------------------------

keywords:     minimal academic
description:  The Strata Academic is a simple and elegant jekyll theme for academic personal homepage.
canonical:    https://strata-academic.yyliu.net/
remote_theme: yaoyao-liu/strata-academic

# -----------------------------------------------------------------------------
# Personal Info
# -----------------------------------------------------------------------------

title:              Mafalda Sofia Ferreira
position:           First Stage Researcher (R1)
affiliation:        Instituto Superior Técnico / INESC-ID
location:           Lisbon, Portugal
email:              mafaldasofiacf@tecnico.ulisboa.pt
google_scholar_id:  #YadkawUAAAAJ
linkedin_username:  mafaldasofiacf
github_username:    mafaldacf
orcid_id:           #0009-0008-9659-4849
cv_link:            https://mafaldacf.github.io/docs/cv.pdf
avatar:             ./assets/img/photo.png # could just be square but we use it in the icon page as well

# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------

enable_google_analytics:    true
enable_google_verification: false
enable_darkmode:            true

# -----------------------------------------------------------------------------
# Analytics and search engine verification
# -----------------------------------------------------------------------------

google_analytics:  # your Goole Analytics measurement ID (format: G-XXXXXXXXXX)
google_site_verification:  # your google-site-verification ID (Google Search Console)
bing_site_verification:  # out your bing-site-verification ID (Bing Webmaster)
